### ISSUE TITLE
ASP.NET - TP Faire un site web pour rechercher une recette

### ISSUE THREAD

**Issue by NitriKx** [NitriKx/M2DL-ACEE-TPs-CSharp#3]
Faire un site web avec des Web Forms, qui permet de rechercher une recette dans la base de données, grâce aux service crées précédemment.

**Comment by serut** [comment]
Ohhh excellent ! Vivement !

**Comment by serut** [comment]
Ok !

**Comment by superkebab** [comment]
Pardon, ou se trouvent les WC ?

**Comment by NitriKx** [comment]
https://www.google.fr/maps/dir/43.5619868,1.4704438/43.5622227,1.4697402/@43.5622023,1.4695104,19z/data=!3m1!4b1!4m5!4m4!1m1!4e1!1m0!3e2
